blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'

urlpatterns = [
    # groupのpkです
    path('post_create/<int:group_pk>/', views.create_post, name='create_post'),
    # blogのpkです
    path('post_detail/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('post_update/<int:pk>/', views.PostUpdate.as_view(), name='update_post'),
    path('post_delete/<int:pk>/', views.PostDelete.as_view(), name='delete_post'),
    # groupのpkです
    path('post_list/<int:group_pk>/', views.PostList.as_view(), name='post_list'),
    path('recent_post_list/', views.RecentPostList.as_view(), name='recent_post_list'),

    path('comment_list/<int:group_pk>/', views.BlogCommentList.as_view(), name='comment_list'),
    # コメントのpkです
    path('comment/<int:postcomment_pk>/', views.BlogCommentDetail.as_view(), name='comment_detail'),
    # path('delete_post/<int:post_pk>', views.DeletePost.as_view(), name='delete_post'),
    # path('delete_post_done/', views.DeletePostDone.as_view(), name='delete_post_done'),

]

events/urls.py
from django.urls import path
from . import views


app_name= 'events'

urlpatterns = [
    # groupのpkです
    path('event_create/<int:group_pk>/', views.create_event, name='create_event'),
    # eventのpkです
    path('event_detail/<int:event_pk>/', views.event_detail, name='event_detail'),
    path('event_update/<int:pk>/', views.EventUpdate.as_view(), name='update_event'),
    path('event_delete/<int:pk>/', views.EventDelete.as_view(), name='delete_event'),
    # groupのpkです
    path('event_list/<int:group_pk>/', views.event_list, name='event_list'),
    path('event_join_list/', views.EventJoinList.as_view(), name='event_join_list'),
    path('recent_event_list/', views.RecentEventList.as_view(), name='recent_event_list'),
    path('all_comment_list/', views.AllEventCommentList.as_view(), name='all_comment_list'),

    path('comment_list/<int:event_pk>/', views.EventCommentList.as_view(), name='comment_list'),
    # コメントのpkです
    path('comment/<int:eventcomment_pk>/', views.EventCommentDetail.as_view(), name='comment_detail'),
    # eventのpk
    path('event_join/<int:event_pk>/', views.join_event, name='event_join'),

    path('event_cancel/<int:event_pk>/', views.CancelEvent.as_view(), name='cancel_event'),
    path('event_cancel_done/', views.CancelEventDone.as_view(), name='cancel_event_done'),
    # path('delete_event/<int:event_pk>', views.DeleteEvent.as_view(), name='delete_event'),
    # path('delete_event_done/', views.DeleteEventDone.as_view(), name='delete_event_done'),

]

group/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'group'

urlpatterns = [
    path('before_create/', views.BeforeCreate.as_view(), name='before_create'),
    path('group_create/', views.create_group, name='create_group'),
    # path('group_create/', views.CreateGroup.as_view(), name='create_group'),
    path('group_create_done/', views.GroupCreateDone.as_view(), name='group_create_done'),
    path('group_detail/<int:group_pk>', views.group_detail, name='group_detail'),

    # groupのpk
    path('group_update/<int:group_pk>', views.update_group, name='update_group'),
    path('group_join/<int:group_pk>', views.join_group, name='group_join'),
    path('group_not_display/', views.GroupNotDisplay.as_view(), name='group_not_display'),
    path('group_list/', views.group_list, name='group_list'),
    path('<int:group_pk>/approve_user/<int:user_pk>/', views.approve_applied_user, name='approve_user'),
    path('apply_administrator/<int:user_pk>/<int:group_pk>/', views.apply_administrator, name='apply_administrator'),
    path('admit_being_administrator/<int:user_pk>/<int:group_pk>/', views.admit_being_administrator, name='admit_being_administrator'),


    path('remove_user/<int:user_pk>/<int:group_pk>/', views.remove_user_from_group, name='remove_user'),
    path('group_member_list/<int:group_pk>/', views.GroupMemberList.as_view(), name='group_member_list'),
    path('group_member_list_for_all/<int:group_pk>/', views.GroupMemberListForAll.as_view(), name='group_member_list_for_all'),
    path('group_administrator_list_for_all/<int:group_pk>/', views.GroupAdministratorListForAll.as_view(), name='group_administrator_list_for_all'),
    path('leave_group/<int:group_pk>', views.LeaveGroup.as_view(), name='leave_group'),
    path('leave_group_done/', views.LeaveGroupDone.as_view(), name='leave_group_done'),
    path('delete_group/<int:group_pk>', views.DeleteGroup.as_view(), name='delete_group'),
    path('delete_group_done/', views.DeleteGroupDone.as_view(), name='delete_group_done'),
    path('managing_group/<int:group_pk>', views.ManageGroup.as_view(), name='managing_group'),
    path('belonging_group/', views.BelongingGroupList.as_view(), name='belonging_group'),
    path('belonging_group_info/<int:group_pk>', views.BelongingGroupInfo.as_view(), name='belonging_group_info'),
    path('group_info/<int:group_pk>', views.BelongingGroupInfo.as_view(), name='belonging_group_info'),
    path('stop_recruiting_member/<int:group_pk>', views.StopRecruitingMember.as_view(), name='stop_recruiting_member'),
]

users/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    # profileのpkです
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),

    # profileのpkです
    path('username_change/<int:pk>/', views.UserNameChange.as_view(), name='username_change'),
    path('profile_change/<int:pk>/', views.ProfileChange.as_view(), name='profile_change'),
    path('account_delete/', views.AccountDelete.as_view(), name='delete_account'),
    path('user_config/', views.UserConfig.as_view(), name='user_config'),
    path('terms_of_service/', views.TermsOfService.as_view(), name='terms_of_service'),
    path('privacy_policy/', views.PrivacyPolicy.as_view(), name='privacy_policy'),

]

events/models.py
import datetime
from django.db import models

# from imagekit.models import ImageSpecField
# from imagekit.processors import ResizeToFill

from group.models import Group, GroupPrefecture
from users.models import CustomUser, Profile





class Event(models.Model):
    posted_group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='投稿グループ')
    title = models.CharField(max_length=60, verbose_name='タイトル')
    content = models.CharField(max_length=1000, verbose_name='本文')
    posted_at = models.DateTimeField(auto_now_add=True, verbose_name='投稿日')
    prefecture = models.ManyToManyField(GroupPrefecture, verbose_name='都道府県')
    detail_place = models.CharField(max_length=200, verbose_name='活動場所')
    event_day = models.DateField(verbose_name='開催日')
    event_end_day = models.DateField(null=True, blank=True, default='')
    time_description = models.CharField(max_length=200,default='', null=True, blank=True, verbose_name='開催時間・予定日の補足情報')
    joinned_user = models.ManyToManyField(Profile, verbose_name='参加者', blank=True)


    image1 = models.ImageField(
        upload_to="group_event_image1/%y/%m/%d/",
        verbose_name='イベント画像1枚目',
        null=True,
        blank=True,
    )
    # thumbnail1 = ImageSpecField(source='image1',
    #                             processors=[ResizeToFill(800, 800)],
    #                             format="JPEG",
    #                             # options={'quality': 60}
    #                             )

    image2 = models.ImageField(
        upload_to="group_event_image2/%y/%m/%d/",
        null=True,
        blank=True,
        verbose_name='イベント画像2枚目',
    )
    # thumbnail2 = ImageSpecField(source='image2',
    #                             processors=[ResizeToFill(500, 500)],
    #                             format="JPEG",
    #                             # options={'quality': 60}
    #                             )

    image3 = models.ImageField(
        upload_to="group_event_image3/%y/%m/%d/",
        null=True,
        blank=True,
        verbose_name='イベント画像3枚目',
    )
    # thumbnail3 = ImageSpecField(source='image3',
    #                             processors=[ResizeToFill(500, 500)],
    #                             format="JPEG",
    #                             # options={'quality': 60}
    #                             )

    def __str__(self):
        return self.title

class EventComment(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name='紐付く投稿')
    comment = models.CharField(max_length=200, verbose_name='コメント')
    commented_at = models.DateTimeField(auto_now_add=True, verbose_name='コメント日')
    user = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        verbose_name='ユーザー',
    )

    def __str__(self):
        return self.comment

class EventCommentMessage(models.Model):
    administrator = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='管理者')
    has_read = models.BooleanField(default=False, verbose_name='既読')
    comment = models.ForeignKey(EventComment, on_delete=models.CASCADE, verbose_name='コメント')


    def __str__(self):
        return str(self.comment) + ' for ' + str(self.administrator)

group/forms.py
from django import forms


from users.models import Profile
from message.models import ApplyAdministratorMessage

from .models import(
    Group,
    GroupPrefecture,
    GroupGeneration,
    GroupCategory,
)




class BeforeCreateConsentForm(forms.Form):
    consent = forms.BooleanField(required=True, label='同意する')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-horizontal'


class FileInputWithPreview(forms.ClearableFileInput):
    """プレビュー表示されるinput type=file"""
    template_name = 'widgets/file_input_with_preview.html'

    class Media:
        js = ['js/preview.js']

    def __init__(self, attrs=None, include_preview=True):
        super().__init__(attrs)
        if 'class' in self.attrs:
            self.attrs['class'] += ' preview-marker'
        else:
            self.attrs['class'] = 'preview-marker'
        self.include_preview = include_preview

    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        context['widget'].update({
            'include_preview': self.include_preview,
        })
        return context

class CustomModelChoiceIterator(forms.models.ModelChoiceIterator):
    def choice(self, obj):
        # print(obj)
        return (self.field.prepare_value(obj),
                self.field.label_from_instance(obj), obj)

class CustomModelChoiceField(forms.models.ModelMultipleChoiceField):
    def _get_choices(self):
        if hasattr(self, '_choices'):
            return self._choices
        return CustomModelChoiceIterator(self)
    choices = property(_get_choices,
                       forms.MultipleChoiceField._set_choices)

class GroupCreateForm(forms.ModelForm):

    prefecture = CustomModelChoiceField(widget=forms.CheckboxSelectMultiple, queryset=GroupPrefecture.objects.all())

    category = CustomModelChoiceField(
        queryset=GroupCategory.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )



    class Meta:
        model = Group
        fields = [
            'name',
            'subtitle',
            'activity_description',
            'mood',
            'welcome_person',
            'sex_ratio',
            'number_of_members',
            'max_age',
            'min_age',
            'cost',
            'day',
            'generation',
            'category',
            'last_comment',
            'detail_place',
            'founded_date',
            'prefecture',
            'image1',
            'image2',
            'image3',
        ]

        widgets = {
            'name': forms.TextInput(attrs={'style': 'width:80%','class': 'form-control'}),
            'subtitle': forms.Textarea(attrs={'style': 'width:80%;','class': 'form-control'}),
            'activity_description': forms.Textarea(attrs={'style': 'width:80%;','class': 'form-control'}),
            'mood': forms.Textarea(attrs={'style': 'width:80%;','class': 'form-control'}),
            'welcome_person': forms.Textarea(attrs={'style': 'width:80%;','class': 'form-control'}),
            'number_of_members': forms.NumberInput(attrs={'style': 'width:90px;','class': 'form-horizontal'}),
            'founded_date': forms.SelectDateWidget,
            'sex_ratio':forms.Textarea(attrs={'style': 'height:70px; width:40%','class': 'form-control'}),
            'max_age': forms.NumberInput(attrs={'style': 'width:90px;','class': 'form-horizontal'}),
            'min_age': forms.NumberInput(attrs={ 'style': 'width:90px;','class': 'form-horizontal'}),
            'cost': forms.Textarea(attrs={'style': 'height:70px; width:60%','class': 'form-control'}),
            'day': forms.Textarea(attrs={'style': 'height:70px; width:60%','class': 'form-control'}),
            # 'category': CustomModelChoiceField(queryset=GroupCategory.objects.all()),
            'generation': forms.CheckboxSelectMultiple(),
            'prefecture': forms.CheckboxSelectMultiple(),
            'last_comment': forms.Textarea(attrs={'style': 'width:80%;','class': 'form-control'}),
            'detail_place': forms.Textarea(attrs={'style': 'width:80%;','class': 'form-control'}),
            'image1': FileInputWithPreview(attrs={
                'class': "form-control-file",
            }),
            'image2': FileInputWithPreview(attrs={
                'class': "form-control-file",
            }),
            'image3': FileInputWithPreview(attrs={
                'class': "form-control-file",
            }),
        }


    def clean_prefecture(self):
        prefecture = []
        try:
            prefecture = self.cleaned_data['prefecture']
        except KeyError:
            pass

        total_prefecture_count = len(prefecture)
        if total_prefecture_count == 0:
            raise forms.ValidationError('都道府県は1つ以上選択してください。')

        if total_prefecture_count > 5:
            raise forms.ValidationError('都道府県は5つ以下にしてください。')
        return prefecture



    def clean_generation(self):
        generation = []
        try:
            generation = self.cleaned_data['generation']
        except KeyError:
            pass

        total_prefecture_count = len(generation)
        if total_prefecture_count == 0:
            raise forms.ValidationError('年代は1つ以上選択してください。')
        return generation


    def clean_category(self):
        total_category_count = 0
        try:
            category = self.cleaned_data['category']
        except KeyError:
            pass
        total_category_count = len(category)
        if total_category_count == 0:
            raise forms.ValidationError('カテゴリーは1つ以上選んでください。')

        if total_category_count > 5:
            raise forms.ValidationError('カテゴリは5つまでにしてください。')
        return category










class GroupSearchForm(forms.Form):
    pr = forms.ModelMultipleChoiceField(
        queryset=GroupPrefecture.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    ca = CustomModelChoiceField(
        queryset=GroupCategory.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    ge = CustomModelChoiceField(
        queryset=GroupGeneration.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )


APPLY_OR_REFUSE_CHOICE = (
    ('1', '承認する'),
    ('2', '承認しない')
)

class ApproveOrRefuseUserForm(forms.Form):
    choice = forms.ChoiceField(choices=APPLY_OR_REFUSE_CHOICE, widget=forms.RadioSelect)

class ApplyAdministratorForm(forms.ModelForm):
    class Meta:
        model = ApplyAdministratorMessage
        fields = ['reason']

        widgets = {
            'reason': forms.Textarea,
        }


ADMIT_OR_REFUSE_CHOICE = (
    ('1', '許諾する'),
    ('2', '断る')
)

class AdmitOrRefuseBeingAdministratorForm(forms.Form):
    choice = forms.ChoiceField(choices=ADMIT_OR_REFUSE_CHOICE, widget=forms.RadioSelect)


class RemoveUseForm(forms.Form):
    consent = forms.BooleanField(required=True, label='同意する')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-horizontal'

templates/group/group_create_done.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/group/before_create.css' %}">
{% endblock css %}

{% block content %}
<p>グループの登録申請が完了しました。承認結果をお待ちください。
</p>


{% endblock content %}

templates/group/group_detail.html
{% extends "base.html" %}
{% load static %}

{% load tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/eyecatch_image.css' %}">

<link rel="stylesheet" href="{% static 'css/group/group_detail.css' %}">


{% endblock css %}

{% block content %}


<div class="group">
    <div class="group-title">
        <h1>{{ object.name }}</h1>
    </div>

    {% if object.subtitle %}

        <p>{{ object.subtitle }}</p>
    {% endif %}
</div>

<div class="header-column-wrapper">
    <div class="header-column header-column1">
        <a href="{% url 'group:group_detail' group_pk=object.pk %}" class="header-link"></a>グループ
    </div><!--
 --><div class="header-column header-column2">
        <a href="{% url 'events:event_list' group_pk=object.pk %}" class="header-link"></a>イベント
    </div><!--
    --><div class="header-column header-column3">
        <a href="{% url 'blogs:post_list' group_pk=object.pk %}" class="header-link"></a>ブログ
    </div>
</div>



<div class="image-wrapper">
    <div class="image-subwrapper">
    <div class="group-image-list">

            {% if object.image1 %}






            <div class="group-image-1">
                <img class="image" src="{{ object.image1.url }}">
            </div>
            {% endif %}


            {% if object.image2 %}
            <div class="group-image-2">
            <img class="image" src="{{ object.image2.url }}">
            </div>
            {% endif %}


            {% if object.image3 %}
            <div class="group-image-3">

            <img class="image" src="{{ object.image3.url }}">
            </div>
            {% endif %}


        </div>
    </div>
</div>




    <div class="group">
        <p>活動内容</p>
        <div class="group-content">
            <p>{{ object.activity_description|linebreaksbr }}</p>
        </div>
    </div>


    {% if object.mood %}
    <div class="group">
        <p>雰囲気</p>
        <div class="group-content">

            <p>{{ object.mood|linebreaksbr }}</p>
        </div>
    </div>
    {% endif %}


    {% if object.welcome_person %}
    <div class="group">
        <p>こんな人に来て欲しい</p>
        <div class="group-content">

            <p>{{ object.welcome_person|linebreaksbr }}</p>
        </div>
    </div>
    {% endif %}

    <div class="group">
        都道府県&nbsp;&nbsp;&nbsp;&nbsp;:
        &nbsp;&nbsp;&nbsp;&nbsp;
        {% for each_prefecture in object.prefecture.all %}
            <div class="group-tag">
                {{ each_prefecture.get_prefecture_display }}
            </div>
        {% endfor %}

    </div>

    <div class="group">
        主な年代&nbsp;&nbsp;&nbsp;&nbsp;:
        &nbsp;&nbsp;&nbsp;&nbsp;
        {% for each_generation in object.generation.all %}
            <div class="group-tag">
                {{ each_generation.get_generation_display }}
            </div>
        {% endfor %}
    </div>
    {% if object.min_age or object.max_age %}
    <div class="group">
        <p>年齢層&nbsp;&nbsp;&nbsp;&nbsp;:
        &nbsp;&nbsp;&nbsp;&nbsp;

             {% if object.min_age  %}{{ object.min_age }}才{% endif %}〜{% if object.min_age %}{{ object.max_age }}才{% endif %}
        </p>
    </div>
    {% endif %}

    <div class="group">
        <p>メンバー数&nbsp;&nbsp;&nbsp;&nbsp;:
        &nbsp;&nbsp;&nbsp;&nbsp;
         {{ object.number_of_members }}人
        </p>
    </div>



    {% if object.day %}
    <div class="group">
        <p>活動頻度</p>
        <div class="group-content">

            <p>{{ object.day|linebreaksbr }}</p>
        </div>
    </div>
    {% endif %}




    {% if object.detail_place %}
    <div class="group">
        <p>主な活動場所</p>
        <div class="group-content">

            <p>{{ object.detail_place|linebreaksbr }}</p>
        </div>
    </div>
    {% endif %}




    {% if object.sex_ratio %}

        <div class="group">

            <p>ジェンダー比</p>
            <div class="group-content">
                {{ object.sex_ratio }}
            </div>
        </div>
    {% endif %}


    {% if object.cost %}
    <div class="group">
        <p>会費について</p>
        <div class="group group-content">
            <p>{{ object.cost|linebreaksbr }}</p>
        </div>
    </div>
    {% endif %}


    <div class="group">
        カテゴリー&nbsp;&nbsp;&nbsp;&nbsp;:
        &nbsp;&nbsp;&nbsp;&nbsp;
        {% for each_category in object.category.all %}
            <div class="group-tag">
                {{ each_category.get_category_display }}
            </div>
        {% endfor %}

    </div>

<div class="join-group">
    {% if request.user.is_authenticated %}
        {% request_user_is_in_the_group %}
    {% else %}
    <p class="need-signup">※ グループに参加するには会員登録が必要です。</p>
    {% endif %}

</div>



<div class="user-list">
    <h2>メンバー</h2>
        {% for each_member in members %}
            <div class="user">
                <a href="{% url 'users:user_detail' pk=each_member.pk %}" class="user-link"></a> &nbsp;&nbsp;&nbsp;

                <div class="user-body row">
                    <div class="col-5 col-sm-6 col-md-3 col-lg-4 user-image-parent">

                        {% if each_member.origin %}
                            <div class="image-wrapper">
                                <div class="image-subwrapper">
                                    <img class="image"  src="{{ each_member.origin.url }}">
                                    </div>
                                </div>
                        {% else %}
                            <p class="no-image">No Image</p>


                        {% endif %}
                    </div>
                    <div class="col-7 col-sm-6 col-md-6  offset-md-1 col-lg-6 user-sentence">
                        <div class="name">
                            {{ each_member.user.user_name }}
                        </div>
                        {% if each_member.profile %}
                            <div class="profile">

                                    {{ each_member.profile }}

                            </div>
                        {% endif %}

                    </div>

                </div>
            </div>
        {% endfor %}

    {% if members %}
    <a href="{% url 'group:group_member_list_for_all' group_pk=object.pk %}">メンバー一覧</a>
    {% endif %}
</div>


<div class="user-list">
    <h2>代表</h2>
        {% for each_administrator in administrators %}
        <div class="user">
            <a href="{% url 'users:user_detail' pk=each_administrator.pk %}" class="user-link"></a> &nbsp;&nbsp;&nbsp;

            <div class="user-body row">
                <div class="col-5 col-sm-6 col-md-3 col-lg-4 post-image-parent">
                    <div class="image-wrapper">
                        <div class="image-subwrapper">
                            {% if each_administrator.origin %}

                                <img class="image"  src="{{ each_administrator.origin.url }}">

                            {% else %}
                                <p class="no-image">No Image</p>

                            {% endif %}
                        </div>
                    </div>
            </div>
                <div class="col-7 col-sm-6 col-md-6  offset-md-1 col-lg-6 user-sentence">
                    <div class="name">
                        {{ each_administrator.user.user_name }}
                    </div>

                    <div class="profile">
                        {% if each_administrator.profile %}
                            {{ each_administrator.profile }}
                        {% endif %}
                    </div>


                </div>

            </div>
        </div>
        {% endfor %}
    {% if administrators %}
    <a href="{% url 'group:group_administrator_list_for_all' group_pk=object.pk %}">管理者一覧</a>
    {% endif %}

</div>




<div class="post-list">
    <h2>最近の投稿</h2>
        {% for post in posts %}
        <div class="post">
            <a href="{% url 'blogs:post_detail' post_pk=post.pk %}" class="post-link"></a>
            <div class="posted-at">
                <small>{{ post.posted_at }}</small>
            </div>

            <div class="post-body row">



                <div class="col-5 col-sm-6 col-md-3 col-lg-4 post-image-parent">
                    {% if post.image1 %}
                        <div class="image-wrapper">
                            <div class="image-subwrapper">
                                <img class="image"  src="{{ post.image1.url }}">
                            </div>
                        </div>
                    {% else %}
                        <p class="no-image">No Image</p>
                     {% endif %}
                </div>


                <div class="col-7 col-sm-6 col-md-6  offset-md-1 col-lg-6 post-sentence">
                    {% if post.title %}
                    <div class="title">
                        {{ post.title|truncatechars:30 }}
                    </div>
                    {% endif %}


                    <div class="content">
                        {{ post.content|truncatechars:30 }}
                    </div>

                </div>

            </div>
        </div>
        {% endfor %}
    {% if posts %}
        <a href="{% url 'blogs:post_list' group_pk=object.pk %}">もっと見る</a>
        {% else %}
        まだ投稿がありません。
    {% endif %}
</div>


<div class="event-list">
    <h2>イベント</h2>
        {% for event in events %}
        <div class="event">
            <a href="{% url 'events:event_detail' event_pk=event.pk %}" class="event-link"></a>

            <div class="posted-at">
                <small>{{ event.posted_at }}</small>
            </div>
            <div class="post-body row">
                <div class="col-5 col-sm-6 col-md-3 col-lg-4 post-image-parent">
                    {% if event.image1 %}
                       <img class="event-image"  src="{{ event.image1.url }}">
                    {% else %}
                        <p class="no-image">No Image</p>

                    {% endif %}
                </div>
                <div class="col-7 col-sm-6 col-md-6  offset-md-1 col-lg-6 event-sentence">
                        <div class="title">
                            {{ event.title|truncatechars:30 }}
                        </div>
                    <div class="content">
                        {{ event.content|truncatechars:30  }}
                    </div>



                    <div class="place">
                        開催地&nbsp;&nbsp;:&nbsp;&nbsp;
                            {% for each_prefecture in event.prefecture.all %}
                                <div class="group-tag">
                                    {{ each_prefecture }}
                                </div>
                            {% endfor %}

                    </div>

                    <div class="time">
                        {% if event.event_end_day %}

                                開催期間&nbsp;&nbsp;:&nbsp;&nbsp;{{ event.event_day }} &nbsp;&nbsp;〜&nbsp;&nbsp; {{ event.event_end_day }}&nbsp;&nbsp;

                        {% else %}

                                開催日&nbsp;&nbsp;:&nbsp;&nbsp;{{ event.event_day }}

                        {% endif %}
                    </div>

                </div>

            </div>
        </div>
        {% endfor %}
    {% if events %}
        <a href="{% url 'events:event_list' group_pk=object.pk %}">もっと見る</a>
        {% else %}
        まだ投稿がありません。
    {% endif %}
</div>

















{% endblock content %}

templates/group/group_member_list.html
{% extends "base.html" %}
{% load static %}
{%  load tags %}

{% block css %}

{% endblock css %}

{% block content %}
    <h1>{{ group.name }}</h1>



    {% for member in members %}


    {% if member.user.origin %}
        <img width="30%"  src="{{ member.user.url }}">
    {% endif %}{{ member.user.user_name }}<br>
<a href="{% url 'group:remove_user' group_pk=group.pk user_pk=member.pk %}">削除する</a>&nbsp;&nbsp;&nbsp;&nbsp;
<a href="{% url 'group:apply_administrator' group_pk=group.pk user_pk=member.pk %}">管理者になるよう依頼する</a>

    {% endfor %}



{% endblock content %}