blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'

urlpatterns = [
    # groupのpkです
    path('post_create/<int:group_pk>/', views.create_post, name='create_post'),
    # blogのpkです
    path('post_detail/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('post_update/<int:pk>/', views.PostUpdate.as_view(), name='update_post'),
    path('post_delete/<int:pk>/', views.PostDelete.as_view(), name='delete_post'),
    # groupのpkです
    path('post_list/<int:group_pk>/', views.PostList.as_view(), name='post_list'),
    path('recent_post_list/', views.RecentPostList.as_view(), name='recent_post_list'),

    path('comment_list/<int:group_pk>/', views.BlogCommentList.as_view(), name='comment_list'),
    # コメントのpkです
    path('comment/<int:postcomment_pk>/', views.BlogCommentDetail.as_view(), name='comment_detail'),
    # path('delete_post/<int:post_pk>', views.DeletePost.as_view(), name='delete_post'),
    # path('delete_post_done/', views.DeletePostDone.as_view(), name='delete_post_done'),

]

events/urls.py
from django.urls import path
from . import views


app_name= 'events'

urlpatterns = [
    # groupのpkです
    path('event_create/<int:group_pk>/', views.create_event, name='create_event'),
    # eventのpkです
    path('event_detail/<int:event_pk>/', views.event_detail, name='event_detail'),
    path('event_update/<int:pk>/', views.EventUpdate.as_view(), name='update_event'),
    path('event_delete/<int:pk>/', views.EventDelete.as_view(), name='delete_event'),
    # groupのpkです
    path('event_list/<int:group_pk>/', views.event_list, name='event_list'),
    path('event_join_list/', views.EventJoinList.as_view(), name='event_join_list'),
    path('recent_event_list/', views.RecentEventList.as_view(), name='recent_event_list'),
    path('all_comment_list/', views.AllEventCommentList.as_view(), name='all_comment_list'),

    path('comment_list/<int:event_pk>/', views.EventCommentList.as_view(), name='comment_list'),
    # コメントのpkです
    path('comment/<int:eventcomment_pk>/', views.EventCommentDetail.as_view(), name='comment_detail'),
    # eventのpk
    path('event_join/<int:event_pk>/', views.join_event, name='event_join'),

    path('event_cancel/<int:event_pk>/', views.CancelEvent.as_view(), name='cancel_event'),
    path('event_cancel_done/', views.CancelEventDone.as_view(), name='cancel_event_done'),
    # path('delete_event/<int:event_pk>', views.DeleteEvent.as_view(), name='delete_event'),
    # path('delete_event_done/', views.DeleteEventDone.as_view(), name='delete_event_done'),

]

group/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'group'

urlpatterns = [
    path('before_create/', views.BeforeCreate.as_view(), name='before_create'),
    path('group_create/', views.create_group, name='create_group'),
    # path('group_create/', views.CreateGroup.as_view(), name='create_group'),
    path('group_create_done/', views.GroupCreateDone.as_view(), name='group_create_done'),
    path('group_detail/<int:group_pk>', views.group_detail, name='group_detail'),

    # groupのpk
    path('group_update/<int:group_pk>', views.update_group, name='update_group'),
    path('group_join/<int:group_pk>', views.join_group, name='group_join'),
    path('group_not_display/', views.GroupNotDisplay.as_view(), name='group_not_display'),
    path('group_list/', views.group_list, name='group_list'),
    path('<int:group_pk>/approve_user/<int:user_pk>/', views.approve_applied_user, name='approve_user'),
    path('apply_administrator/<int:user_pk>/<int:group_pk>/', views.apply_administrator, name='apply_administrator'),
    path('admit_being_administrator/<int:user_pk>/<int:group_pk>/', views.admit_being_administrator, name='admit_being_administrator'),


    path('remove_user/<int:user_pk>/<int:group_pk>/', views.remove_user_from_group, name='remove_user'),
    path('group_member_list/<int:group_pk>/', views.GroupMemberList.as_view(), name='group_member_list'),
    path('group_member_list_for_all/<int:group_pk>/', views.GroupMemberListForAll.as_view(), name='group_member_list_for_all'),
    path('group_administrator_list_for_all/<int:group_pk>/', views.GroupAdministratorListForAll.as_view(), name='group_administrator_list_for_all'),
    path('leave_group/<int:group_pk>', views.LeaveGroup.as_view(), name='leave_group'),
    path('leave_group_done/', views.LeaveGroupDone.as_view(), name='leave_group_done'),
    path('delete_group/<int:group_pk>', views.DeleteGroup.as_view(), name='delete_group'),
    path('delete_group_done/', views.DeleteGroupDone.as_view(), name='delete_group_done'),
    path('managing_group/<int:group_pk>', views.ManageGroup.as_view(), name='managing_group'),
    path('belonging_group/', views.BelongingGroupList.as_view(), name='belonging_group'),
    path('belonging_group_info/<int:group_pk>', views.BelongingGroupInfo.as_view(), name='belonging_group_info'),
    path('group_info/<int:group_pk>', views.BelongingGroupInfo.as_view(), name='belonging_group_info'),
    path('stop_recruiting_member/<int:group_pk>', views.StopRecruitingMember.as_view(), name='stop_recruiting_member'),
]

message/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'message'

urlpatterns = [
    # グループのpk
    path('inner_group_message_create/<int:group_pk>', views.InnerGroupMessageCreate.as_view(), name='create_inner_group_message'),
    path('inner_group_message_list/<int:group_pk>.', views.InnerGroupMessageList.as_view(), name='inner_group_message_list'),

    # eventのpk
    path('event_message_create/<int:event_pk>/', views.EventMessageCreate.as_view(), name='create_event_message'),

    # userのpk
    path('message_list/', views.message_list, name='message_list'),
    path('each_event_message_list/<int:event_pk>/', views.EachEventMessageList.as_view(), name='each_event_message_list'),
    path('event_message_list/', views.EventMessageList.as_view(), name='event_message_list'),
    path('event_message_list_for_host/<int:event_pk>', views.EventMessageListForHost.as_view(), name='event_message_list_for_host'),
    path('event_join_message_list/<int:event_pk>/', views.EachEventJoinMessageList.as_view(), name='event_join_message_list'),
    path('group_apply_message_list/<int:group_pk>/', views.EachGroupApplyMessageList.as_view(), name='group_apply_message_list'),
    path('event_comment_message_list/<int:event_pk>/', views.EachEventCommentMessageList.as_view(), name='event_comment_message_list'),
    path('post_comment_message_list/<int:post_pk>/', views.EachPostCommentMessageList.as_view(),name='post_comment_message_list'),

    # userのpk
    path('admin_message_list/', views.AdminMessageList.as_view(), name='admin_message_list'),


    # path('group_create_done/', views.GroupCreateDone.as_view(), name='group_create_done'),
    # path('group_detail/<int:pk>', views.group_detail, name='group_detail'),
    # path('group_join/<int:pk>', views.join_group, name='group_join'),
    # path('group_not_display/', views.GroupNotDisplay.as_view(), name='group_not_display'),
    # # path('group_list/', views.GroupList.as_view(), name='group_list'),
    # path('group_list/', views.post_index, name='group_list'),
    # path('<int:group_pk>/approve_user/<int:user_pk>/', views.approve_applied_user, name='approve_user'),


]

users/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    # profileのpkです
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),

    # profileのpkです
    path('username_change/<int:pk>/', views.UserNameChange.as_view(), name='username_change'),
    path('profile_change/<int:pk>/', views.ProfileChange.as_view(), name='profile_change'),
    path('account_delete/', views.AccountDelete.as_view(), name='delete_account'),
    path('user_config/', views.UserConfig.as_view(), name='user_config'),
    path('terms_of_service/', views.TermsOfService.as_view(), name='terms_of_service'),
    path('privacy_policy/', views.PrivacyPolicy.as_view(), name='privacy_policy'),

]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
      {% block css %}

      {% endblock css %}

    <title>{% block title %}Ocealena{% endblock title %}</title>
  </head>
  <body>
  {% include 'navbar.html' %}
  <div class="container">
    {% block content %}
    {% endblock content %}

  </div>
{% include 'footer.html' %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  {% block js %}
    {% endblock js %}
  </body>
</html>

templates/footer.html
  <div class="footer-wrapper">
    <footer>
        <p><a href="{% url 'users:terms_of_service' %}">利用規約</a></p>
        <p><a href="{% url 'users:privacy_policy' %}">プライバシーポリシー</a></p>

      <p>(c)&nbsp;&nbsp;2019&nbsp;&nbsp;Ocealena</p>
    </footer>
  </div>

templates/navbar.html
{% load message_tags %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'group:group_list' %}">Ocealena</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <!--<li class="nav-item active">-->
        <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
      <!--</li>-->
      {% if request.user.is_authenticated %}
        {% if profile_user_id %}

        <li>
          <a class="nav-link" href="{% url 'users:user_detail' pk=profile_user_id %}">{{ request.user.user_name }}さん</a>
        </li>
      {% endif %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'message:message_list'%}">メッセージ&nbsp;&nbsp;{% count_new_message request %}</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:user_config'%}">ユーザー設定</a>
        </li>

        <li>
          <a class="nav-link" href="{% url 'group:belonging_group' %}">グループ</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'events:event_join_list' %}">イベント</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'group:create_group' %}">グループ作成</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'users:logout' %}">ログアウト</a>
        </li>
      {% else %}
        <li>
          <a class="nav-link" href="{% url 'users:login' %}">ログイン</a>
        </li>
        <li>
          <a class="nav-link" href="{% url 'users:signup' %}">新規登録</a>
        </li>

      {% endif %}
    </ul>
  </div>
</nav>

templates/pagination.html
{%  load tags %}


<ul class="pagination">
    <!-- 前へ の部分 -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?{%  url_replace request 'page' page_obj.previous_page_number %}">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
    {% endif %}

    <!-- 数字の部分 -->
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
        {% elif page_obj.number|add:-5 <= num and num <= page_obj.number|add:5 %}
            <li class="page-item"><a class="page-link" href="?{%  url_replace request 'page' num %}">{{ num }}</a></li>
        {% endif %}
    {% endfor %}

    <!-- 次へ の部分 -->
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?{%  url_replace request 'page' page_obj.next_page_number %}">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    {% endif %}
</ul>