blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'

urlpatterns = [
    # groupのpkです
    path('post_create/<int:group_pk>/', views.create_post, name='create_post'),
    # blogのpkです
    path('post_detail/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('post_update/<int:pk>/', views.PostUpdate.as_view(), name='update_post'),
    path('post_delete/<int:pk>/', views.PostDelete.as_view(), name='delete_post'),
    # groupのpkです
    path('post_list/<int:group_pk>/', views.PostList.as_view(), name='post_list'),
    path('recent_post_list/', views.RecentPostList.as_view(), name='recent_post_list'),

    path('comment_list/<int:group_pk>/', views.BlogCommentList.as_view(), name='comment_list'),
    # コメントのpkです
    path('comment/<int:postcomment_pk>/', views.BlogCommentDetail.as_view(), name='comment_detail'),
    # path('delete_post/<int:post_pk>', views.DeletePost.as_view(), name='delete_post'),
    # path('delete_post_done/', views.DeletePostDone.as_view(), name='delete_post_done'),

]

events/urls.py
from django.urls import path
from . import views


app_name= 'events'

urlpatterns = [
    # groupのpkです
    path('event_create/<int:group_pk>/', views.create_event, name='create_event'),
    # eventのpkです
    path('event_detail/<int:event_pk>/', views.event_detail, name='event_detail'),
    path('event_update/<int:pk>/', views.EventUpdate.as_view(), name='update_event'),
    path('event_delete/<int:pk>/', views.EventDelete.as_view(), name='delete_event'),
    # groupのpkです
    path('event_list/<int:group_pk>/', views.event_list, name='event_list'),
    path('event_join_list/', views.EventJoinList.as_view(), name='event_join_list'),
    path('recent_event_list/', views.RecentEventList.as_view(), name='recent_event_list'),
    path('all_comment_list/', views.AllEventCommentList.as_view(), name='all_comment_list'),

    path('comment_list/<int:event_pk>/', views.EventCommentList.as_view(), name='comment_list'),
    # コメントのpkです
    path('comment/<int:eventcomment_pk>/', views.EventCommentDetail.as_view(), name='comment_detail'),
    # eventのpk
    path('event_join/<int:event_pk>/', views.join_event, name='event_join'),

    path('event_cancel/<int:event_pk>/', views.CancelEvent.as_view(), name='cancel_event'),
    path('event_cancel_done/', views.CancelEventDone.as_view(), name='cancel_event_done'),
    # path('delete_event/<int:event_pk>', views.DeleteEvent.as_view(), name='delete_event'),
    # path('delete_event_done/', views.DeleteEventDone.as_view(), name='delete_event_done'),

]

message/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'message'

urlpatterns = [
    # グループのpk
    path('inner_group_message_create/<int:group_pk>', views.InnerGroupMessageCreate.as_view(), name='create_inner_group_message'),
    path('inner_group_message_list/<int:group_pk>.', views.InnerGroupMessageList.as_view(), name='inner_group_message_list'),

    # eventのpk
    path('event_message_create/<int:event_pk>/', views.EventMessageCreate.as_view(), name='create_event_message'),

    # userのpk
    path('message_list/', views.message_list, name='message_list'),
    path('each_event_message_list/<int:event_pk>/', views.EachEventMessageList.as_view(), name='each_event_message_list'),
    path('event_message_list/', views.EventMessageList.as_view(), name='event_message_list'),
    path('event_message_list_for_host/<int:event_pk>', views.EventMessageListForHost.as_view(), name='event_message_list_for_host'),
    path('event_join_message_list/<int:event_pk>/', views.EachEventJoinMessageList.as_view(), name='event_join_message_list'),
    path('group_apply_message_list/<int:group_pk>/', views.EachGroupApplyMessageList.as_view(), name='group_apply_message_list'),
    path('event_comment_message_list/<int:event_pk>/', views.EachEventCommentMessageList.as_view(), name='event_comment_message_list'),
    path('post_comment_message_list/<int:post_pk>/', views.EachPostCommentMessageList.as_view(),name='post_comment_message_list'),

    # userのpk
    path('admin_message_list/', views.AdminMessageList.as_view(), name='admin_message_list'),


    # path('group_create_done/', views.GroupCreateDone.as_view(), name='group_create_done'),
    # path('group_detail/<int:pk>', views.group_detail, name='group_detail'),
    # path('group_join/<int:pk>', views.join_group, name='group_join'),
    # path('group_not_display/', views.GroupNotDisplay.as_view(), name='group_not_display'),
    # # path('group_list/', views.GroupList.as_view(), name='group_list'),
    # path('group_list/', views.post_index, name='group_list'),
    # path('<int:group_pk>/approve_user/<int:user_pk>/', views.approve_applied_user, name='approve_user'),


]

users/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    # profileのpkです
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),

    # profileのpkです
    path('username_change/<int:pk>/', views.UserNameChange.as_view(), name='username_change'),
    path('profile_change/<int:pk>/', views.ProfileChange.as_view(), name='profile_change'),
    path('account_delete/', views.AccountDelete.as_view(), name='delete_account'),
    path('user_config/', views.UserConfig.as_view(), name='user_config'),
    path('terms_of_service/', views.TermsOfService.as_view(), name='terms_of_service'),
    path('privacy_policy/', views.PrivacyPolicy.as_view(), name='privacy_policy'),

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver

# from imagekit.models import ImageSpecField
# from imagekit.processors import ResizeToFill

class UserManager(BaseUserManager):
    """ユーザーマネージャー."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """メールアドレスでの登録を必須にする"""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """is_staff(管理サイトにログインできるか)と、is_superuer(全ての権限)をFalseに"""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """スーパーユーザーは、is_staffとis_superuserをTrueに"""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    """カスタムユーザーモデル."""

    email = models.EmailField(_('メールアドレス'), unique=True)
    # username = models.CharField(max_length=30, verbose_name='ニックネーム')
    user_name = models.CharField(max_length=30, verbose_name='ニックネーム')
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('入会日'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')



    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    @property
    def username(self):
        """username属性のゲッター

        他アプリケーションが、username属性にアクセスした場合に備えて定義
        メールアドレスを返す
        """
        return self.email




SEX_CHOICES = (
    ('M', '男性'),
    ('F', '女性'),
    ('X', '第3の性'),
    ('N/A', '回答しない')

)

class Profile(models.Model):
    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='profile_set',
    )
    origin = models.ImageField(
        upload_to="profile_image/%y/%m/%d/",
        null=True,
        blank=True,
        verbose_name='プロフィール画像',
        width_field=''
    )
    # thumbnail = ImageSpecField(source='origin',
    #                            processors=[ResizeToFill(800, 800)],
    #                            format="JPEG",
    #                            # options={'quality': 60}
    #                            )
    profile = models.CharField(
        max_length=500,
        verbose_name='プロフィール',
        null=True,
        blank=True,
        default='',
    )
    sex = models.CharField(max_length=3, choices=SEX_CHOICES, verbose_name='性別', default=None)
    age = models.PositiveIntegerField(null=True, blank=True, verbose_name='年齢')
    twitter_link = models.URLField(null=True, blank=True, default='', verbose_name='Twitterアカウントのリンク')
    facebook_link = models.URLField(null=True, blank=True, default='', verbose_name='Facebookアカウントリンク')
    instagram_link = models.URLField(null=True, blank=True, default='', verbose_name='Instagramアカウントのリンク')

    def __str__(self):
        return str(self.user)

templates/users/account_delete.html
{% extends "base.html" %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <p>退会すると、{{ user.user_name }}さんのアカウントと{{ user.user_name }}さん一人が管理しているグループが削除されます。</p>
    <p>よろしいですか？</p>
    <input type="hidden" name="delete_complete" value="delete_complete">
    <button type="submit" class="btn btn-danger">退会する</button>
</form>
{% endblock content %}

templates/users/cannot_delete.html
{% extends "base.html" %}
{% block content %}
<p>管理者があなた一人のグループが存在します。<br>
    {% for group in only_one_administrator_group_list %}
    グループ名&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{ group.name }}<br>
    {% endfor %}
<p>上記のグループについては退会前に管理者を他のメンバーに託してください。<br>
    もしくは、上記のグループを全て削除しても良い場合は、以下のリンクから退会することができます。</p>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="delete" value="delete">
    <button type="submit" class="btn btn-danger">退会ページ</button>
</form>
{% endblock %}

templates/users/delete_complete.html
{% extends "base.html" %}
{% block content %}

<h1>退会が完了しました。</h1>
<p>ご利用ありがとうございました。またのご利用をお待ちしています。</p>
{% endblock content %}

templates/users/email_change_complete.html
{% extends "base.html" %}
{% block content %}
<p>
    メールアドレスを変更しました。<br>
</p>
{% endblock %}

templates/users/email_change_form.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

templates/users/login.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    <div class="col-md-6 offset-md-3">
        <div class="card">
            <div class="card-body">
                {{ form.non_field_errors }}
                {% for field in form %}
                    {{ field }}
                    {{ field.errors }}
                    <hr>
                {% endfor %}
                <button type="submit" class="btn btn-success btn-lg btn-block" >ログイン</button>
                <input type="hidden" name="next" value="{{ next }}" />
                {% csrf_token %}
            </div>
        </div>
        <br>
        <p>パスワードをお忘れの方は<a href="{% url 'users:password_reset' %}">こちら</a></p>
    </div>
</form>
{% endblock %}

templates/users/password_change.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock %}

templates/users/password_change_done.html
{% extends "base.html" %}
{% block content %}
<p>
    パスワードを変更しました。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'users:login' %}">ログイン</a>
</p>
{% endblock content %}

templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary btn-lg">送信</button>
</form>
{% endblock content %}

templates/users/privacy_policy.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>プライバシーポリシー</h1>
<br>
<h2>個人情報の収集に関して</h2>
<ol>
    <li>本サイトでは、運営からの連絡やユーザ情報の登録・更新のため、個人情報をお尋ねする場合があります。</li>
</ol>
<h2>個人情報の第三者提供</h2>

<p>本サイトでは、次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。</p>
<ol>
    <li>人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</li>
    <li>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</li>
    <li>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
</ol>


{% endblock content %}

templates/users/top.html
{% extends "base.html" %}
{% block content %}
<p>ログアウトしました。</p>
{% endblock %}

templates/users/user_config.html
{% extends "base.html" %}
{% block content %}
<h2><a href="{% url 'users:user_detail' pk=user_profile.pk %}">{{ user_profile.user.user_name }}さん</a></h2><hr>

<div><p><a href="{% url 'message:message_list' %}">最近のメッセージ</a></p></div>
<div>

    <p><a href="{% url 'users:profile_change' pk=user_profile.pk %}">プロフィールを編集する</a></p>
    <p><a href="{% url 'users:username_change' pk=user_profile.pk %}">ニックネームを変更する</a></p>



    <p><a href="{% url 'users:password_change' %}">パスワードを変更する</a></p>
    <p><a href="{% url 'users:email_change' %}">メールアドレスを変更する</a></p>
    <p><a href="{% url 'events:event_join_list' %}">参加したイベント</a></p>

    <p><a href="{% url 'users:delete_account' %}">退会する</a></p>
</div>




{% endblock content %}

templates/users/user_create_complete.html
{% extends "base.html" %}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'users:login' %}">ログイン</a>
</p>
{% endblock %}

templates/users/user_profile.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/users/user_profile.css' %}">
{% endblock css %}


{% block content %}
    <div class="user-image-wrapper">
        <div class="user-image-subwrapper no-image">
            {% if object.origin %}


                <img class="user-img" src="{{ object.origin.url }}">
            {% else %}
                    No Image
         　　{% endif %}
        </div>

    </div>
    <h1>{{ object.user.user_name }}</h1>
    <div class="base-info">
        {% if object.age %}
            <div class="user-age">
                年齢&nbsp;&nbsp;:&nbsp;&nbsp;{{ object.age }}歳
            </div>
        {% endif %}



        {% if not object.sex == 'N/A' %}
            <div class="user-sex">
                性別&nbsp;&nbsp;:&nbsp;&nbsp;{{ object.get_sex_display }}
            </div>
        {% endif %}

    </div>
    <div class="user-profile-wrapper">プロフィール</div>
        {% if object.profile %}

            <div class="user-profile">

                {{ object.profile|linebreaksbr }}

            </div>
        {% else %}
            <p class="no-profile">（まだプロフィールはありません。）</p>
        {% endif %}


    {% if object.twitter_link %}

        <div class="user-link">

            Twitter&nbsp;&nbsp;:&nbsp;&nbsp;{{ object.twitter_link|urlize }}
        </div>

    {% endif %}
    {% if object.facebook_link %}

        <div class="user-link">

            Facebook&nbsp;&nbsp;:&nbsp;&nbsp;{{ object.facebook_link|urlize }}
        </div>

    {% endif %}
    {% if object.instagram_link %}

        <div class="user-link">

            Instagram&nbsp;&nbsp;:&nbsp;&nbsp;{{ object.instagram_link|urlize }}
        </div>
    {% endif %}


{% endblock %}