blogs/urls.py
from django.urls import path
from . import views


app_name = 'blogs'

urlpatterns = [
    # groupのpkです
    path('post_create/<int:group_pk>/', views.create_post, name='create_post'),
    # blogのpkです
    path('post_detail/<int:post_pk>/', views.post_detail, name='post_detail'),
    path('post_update/<int:pk>/', views.PostUpdate.as_view(), name='update_post'),
    path('post_delete/<int:pk>/', views.PostDelete.as_view(), name='delete_post'),
    # groupのpkです
    path('post_list/<int:group_pk>/', views.PostList.as_view(), name='post_list'),
    path('recent_post_list/', views.RecentPostList.as_view(), name='recent_post_list'),

    path('comment_list/<int:group_pk>/', views.BlogCommentList.as_view(), name='comment_list'),
    # コメントのpkです
    path('comment/<int:postcomment_pk>/', views.BlogCommentDetail.as_view(), name='comment_detail'),
    # path('delete_post/<int:post_pk>', views.DeletePost.as_view(), name='delete_post'),
    # path('delete_post_done/', views.DeletePostDone.as_view(), name='delete_post_done'),

]

events/urls.py
from django.urls import path
from . import views


app_name= 'events'

urlpatterns = [
    # groupのpkです
    path('event_create/<int:group_pk>/', views.create_event, name='create_event'),
    # eventのpkです
    path('event_detail/<int:event_pk>/', views.event_detail, name='event_detail'),
    path('event_update/<int:pk>/', views.EventUpdate.as_view(), name='update_event'),
    path('event_delete/<int:pk>/', views.EventDelete.as_view(), name='delete_event'),
    # groupのpkです
    path('event_list/<int:group_pk>/', views.event_list, name='event_list'),
    path('event_join_list/', views.EventJoinList.as_view(), name='event_join_list'),
    path('recent_event_list/', views.RecentEventList.as_view(), name='recent_event_list'),
    path('all_comment_list/', views.AllEventCommentList.as_view(), name='all_comment_list'),

    path('comment_list/<int:event_pk>/', views.EventCommentList.as_view(), name='comment_list'),
    # コメントのpkです
    path('comment/<int:eventcomment_pk>/', views.EventCommentDetail.as_view(), name='comment_detail'),
    # eventのpk
    path('event_join/<int:event_pk>/', views.join_event, name='event_join'),

    path('event_cancel/<int:event_pk>/', views.CancelEvent.as_view(), name='cancel_event'),
    path('event_cancel_done/', views.CancelEventDone.as_view(), name='cancel_event_done'),
    # path('delete_event/<int:event_pk>', views.DeleteEvent.as_view(), name='delete_event'),
    # path('delete_event_done/', views.DeleteEventDone.as_view(), name='delete_event_done'),

]

group/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'group'

urlpatterns = [
    path('before_create/', views.BeforeCreate.as_view(), name='before_create'),
    path('group_create/', views.create_group, name='create_group'),
    # path('group_create/', views.CreateGroup.as_view(), name='create_group'),
    path('group_create_done/', views.GroupCreateDone.as_view(), name='group_create_done'),
    path('group_detail/<int:group_pk>', views.group_detail, name='group_detail'),

    # groupのpk
    path('group_update/<int:group_pk>', views.update_group, name='update_group'),
    path('group_join/<int:group_pk>', views.join_group, name='group_join'),
    path('group_not_display/', views.GroupNotDisplay.as_view(), name='group_not_display'),
    path('group_list/', views.group_list, name='group_list'),
    path('<int:group_pk>/approve_user/<int:user_pk>/', views.approve_applied_user, name='approve_user'),
    path('apply_administrator/<int:user_pk>/<int:group_pk>/', views.apply_administrator, name='apply_administrator'),
    path('admit_being_administrator/<int:user_pk>/<int:group_pk>/', views.admit_being_administrator, name='admit_being_administrator'),


    path('remove_user/<int:user_pk>/<int:group_pk>/', views.remove_user_from_group, name='remove_user'),
    path('group_member_list/<int:group_pk>/', views.GroupMemberList.as_view(), name='group_member_list'),
    path('group_member_list_for_all/<int:group_pk>/', views.GroupMemberListForAll.as_view(), name='group_member_list_for_all'),
    path('group_administrator_list_for_all/<int:group_pk>/', views.GroupAdministratorListForAll.as_view(), name='group_administrator_list_for_all'),
    path('leave_group/<int:group_pk>', views.LeaveGroup.as_view(), name='leave_group'),
    path('leave_group_done/', views.LeaveGroupDone.as_view(), name='leave_group_done'),
    path('delete_group/<int:group_pk>', views.DeleteGroup.as_view(), name='delete_group'),
    path('delete_group_done/', views.DeleteGroupDone.as_view(), name='delete_group_done'),
    path('managing_group/<int:group_pk>', views.ManageGroup.as_view(), name='managing_group'),
    path('belonging_group/', views.BelongingGroupList.as_view(), name='belonging_group'),
    path('belonging_group_info/<int:group_pk>', views.BelongingGroupInfo.as_view(), name='belonging_group_info'),
    path('group_info/<int:group_pk>', views.BelongingGroupInfo.as_view(), name='belonging_group_info'),
    path('stop_recruiting_member/<int:group_pk>', views.StopRecruitingMember.as_view(), name='stop_recruiting_member'),
]

message/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'message'

urlpatterns = [
    # グループのpk
    path('inner_group_message_create/<int:group_pk>', views.InnerGroupMessageCreate.as_view(), name='create_inner_group_message'),
    path('inner_group_message_list/<int:group_pk>.', views.InnerGroupMessageList.as_view(), name='inner_group_message_list'),

    # eventのpk
    path('event_message_create/<int:event_pk>/', views.EventMessageCreate.as_view(), name='create_event_message'),

    # userのpk
    path('message_list/', views.message_list, name='message_list'),
    path('each_event_message_list/<int:event_pk>/', views.EachEventMessageList.as_view(), name='each_event_message_list'),
    path('event_message_list/', views.EventMessageList.as_view(), name='event_message_list'),
    path('event_message_list_for_host/<int:event_pk>', views.EventMessageListForHost.as_view(), name='event_message_list_for_host'),
    path('event_join_message_list/<int:event_pk>/', views.EachEventJoinMessageList.as_view(), name='event_join_message_list'),
    path('group_apply_message_list/<int:group_pk>/', views.EachGroupApplyMessageList.as_view(), name='group_apply_message_list'),
    path('event_comment_message_list/<int:event_pk>/', views.EachEventCommentMessageList.as_view(), name='event_comment_message_list'),
    path('post_comment_message_list/<int:post_pk>/', views.EachPostCommentMessageList.as_view(),name='post_comment_message_list'),

    # userのpk
    path('admin_message_list/', views.AdminMessageList.as_view(), name='admin_message_list'),


    # path('group_create_done/', views.GroupCreateDone.as_view(), name='group_create_done'),
    # path('group_detail/<int:pk>', views.group_detail, name='group_detail'),
    # path('group_join/<int:pk>', views.join_group, name='group_join'),
    # path('group_not_display/', views.GroupNotDisplay.as_view(), name='group_not_display'),
    # # path('group_list/', views.GroupList.as_view(), name='group_list'),
    # path('group_list/', views.post_index, name='group_list'),
    # path('<int:group_pk>/approve_user/<int:user_pk>/', views.approve_applied_user, name='approve_user'),


]

users/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.UserCreate.as_view(), name='signup'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    # profileのpkです
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('email/change/', views.EmailChange.as_view(), name='email_change'),
    path('email/change/done/', views.EmailChangeDone.as_view(), name='email_change_done'),
    path('email/change/complete/<str:token>/', views.EmailChangeComplete.as_view(), name='email_change_complete'),

    # profileのpkです
    path('username_change/<int:pk>/', views.UserNameChange.as_view(), name='username_change'),
    path('profile_change/<int:pk>/', views.ProfileChange.as_view(), name='profile_change'),
    path('account_delete/', views.AccountDelete.as_view(), name='delete_account'),
    path('user_config/', views.UserConfig.as_view(), name='user_config'),
    path('terms_of_service/', views.TermsOfService.as_view(), name='terms_of_service'),
    path('privacy_policy/', views.PrivacyPolicy.as_view(), name='privacy_policy'),

]

events/models.py
import datetime
from django.db import models

# from imagekit.models import ImageSpecField
# from imagekit.processors import ResizeToFill

from group.models import Group, GroupPrefecture
from users.models import CustomUser, Profile





class Event(models.Model):
    posted_group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='投稿グループ')
    title = models.CharField(max_length=60, verbose_name='タイトル')
    content = models.CharField(max_length=1000, verbose_name='本文')
    posted_at = models.DateTimeField(auto_now_add=True, verbose_name='投稿日')
    prefecture = models.ManyToManyField(GroupPrefecture, verbose_name='都道府県')
    detail_place = models.CharField(max_length=200, verbose_name='活動場所')
    event_day = models.DateField(verbose_name='開催日')
    event_end_day = models.DateField(null=True, blank=True, default='')
    time_description = models.CharField(max_length=200,default='', null=True, blank=True, verbose_name='開催時間・予定日の補足情報')
    joinned_user = models.ManyToManyField(Profile, verbose_name='参加者', blank=True)


    image1 = models.ImageField(
        upload_to="group_event_image1/%y/%m/%d/",
        verbose_name='イベント画像1枚目',
        null=True,
        blank=True,
    )
    # thumbnail1 = ImageSpecField(source='image1',
    #                             processors=[ResizeToFill(800, 800)],
    #                             format="JPEG",
    #                             # options={'quality': 60}
    #                             )

    image2 = models.ImageField(
        upload_to="group_event_image2/%y/%m/%d/",
        null=True,
        blank=True,
        verbose_name='イベント画像2枚目',
    )
    # thumbnail2 = ImageSpecField(source='image2',
    #                             processors=[ResizeToFill(500, 500)],
    #                             format="JPEG",
    #                             # options={'quality': 60}
    #                             )

    image3 = models.ImageField(
        upload_to="group_event_image3/%y/%m/%d/",
        null=True,
        blank=True,
        verbose_name='イベント画像3枚目',
    )
    # thumbnail3 = ImageSpecField(source='image3',
    #                             processors=[ResizeToFill(500, 500)],
    #                             format="JPEG",
    #                             # options={'quality': 60}
    #                             )

    def __str__(self):
        return self.title

class EventComment(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, verbose_name='紐付く投稿')
    comment = models.CharField(max_length=200, verbose_name='コメント')
    commented_at = models.DateTimeField(auto_now_add=True, verbose_name='コメント日')
    user = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        verbose_name='ユーザー',
    )

    def __str__(self):
        return self.comment

class EventCommentMessage(models.Model):
    administrator = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='管理者')
    has_read = models.BooleanField(default=False, verbose_name='既読')
    comment = models.ForeignKey(EventComment, on_delete=models.CASCADE, verbose_name='コメント')


    def __str__(self):
        return str(self.comment) + ' for ' + str(self.administrator)

events/forms.py
from django import forms

from .models import Event, EventComment
from group.forms import FileInputWithPreview


class EventCreateForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = [
            'title',
            'content',
            'prefecture',
            'detail_place',
            'event_day',
            'event_end_day',
            'time_description',
            'image1',
            'image2',
            'image3',
        ]


        widgets = {
            'image1': FileInputWithPreview(attrs={
                'class': "form-control-file",
            }),
            'image2': FileInputWithPreview(attrs={
                'class': "form-control-file",
            }),
            'image3': FileInputWithPreview(attrs={
                'class': "form-control-file",
            }),
            'prefecture': forms.CheckboxSelectMultiple,
            'event_day': forms.SelectDateWidget,
            'event_end_day': forms.SelectDateWidget,
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'detail_place': forms.Textarea(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'time_description': forms.Textarea(attrs={'class': 'form-control'}),
        }



class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = EventComment
        fields = ['comment']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

templates/events/all_event_comment.html
{% extends "base.html" %}
{% load event_tags %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/message/message_list.css' %}">
<link rel="stylesheet" href="{% static 'css/events/all_event_comment.css' %}">
{% endblock css %}


{% block content %}


    <div class="message-list">
        <h3>コメント一覧</h3>
        {% for comment in event_comments %}
            <div class="message">
                <div class="message-header">
                        グループ &nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{ comment.event.posted_group.name }}&nbsp;&nbsp;&nbsp;&nbsp;
                        <span>
                        {% autoescape off %}
                            {% has_read request comment %}
                        {% endautoescape %}
                        </span>
                    <small class="sent-at">{{ comment.commented_at }}</small>

                </div>


                <div class="message-body">
                    <div class="content">
                        <div class="event-title">イベント&nbsp;&nbsp;:&nbsp;&nbsp;<a href="{% url 'events:event_detail' event_pk=comment.event.pk %}">{{ comment.event.title|truncatechars:15 }}</a></div>
                        ユーザー&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;<a href="{% url 'users:user_detail' pk=comment.user.pk %}">{{ comment.user.user.user_name|truncatechars:15 }}</a><br><br>
                        {{ comment.comment }}
                    </div><br>
                </div>
                <a href="{% url 'events:event_detail' event_pk=event_comments.first.event.pk %}">コメントをみる</a>
            </div>


        {% endfor %}

        {% if event_comments %}
            {% include 'pagination.html' %}
        {% else %}
            <p>（メッセージはありません。）</p>
        {% endif %}

    </div>


{% endblock %}

templates/events/event_comment.html
{% extends "base.html" %}
{% load event_tags %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/message/message_list.css' %}">
{% endblock css %}


{% block content %}
<big>イベント</big>
<h1>『<a href="{% url 'events:event_detail' event_pk=event_comments.first.event.pk %}">{{ event_comments.first.event.title }}</a>』</h1>へのコメント


    <div class="message-list">
        <h3>コメント一覧</h3>
        {% for comment in event_comments %}
            <div class="message">
                <div class="message-header">
                        グループ &nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;{{ comment.event.posted_group.name }}&nbsp;&nbsp;&nbsp;&nbsp;
                        <span>
                        {% autoescape off %}
                            {% has_read request comment %}
                        {% endautoescape %}
                        </span>
                    <small class="sent-at">{{ comment.commented_at }}</small>

                </div>


                <div class="message-body">
                    <div class="content">
                        ユーザー&nbsp;&nbsp;&nbsp;:&nbsp;&nbsp;&nbsp;<a href="{% url 'users:user_detail' pk=comment.user.pk %}">{{ comment.user.user.user_name|truncatechars:15 }}</a><br><br>
                        {{ comment.comment }}
                    </div><br>
                </div>
                <a href="{% url 'events:event_detail' event_pk=event_comments.first.event.pk %}">コメントをみる</a>
            </div>


        {% endfor %}

        {% if event_comments %}
            {% include 'pagination.html' %}
        {% else %}
            <p>（メッセージはありません。）</p>
        {% endif %}
    </div>


{% endblock %}

templates/events/event_comment_detail.html
{% extends "base.html" %}
{% block content %}
<h1><a href="{% url 'group:group_detail' pk=group.pk %}">{{ group.name }}</a></h1>


    <div>
        <p>{{ object.user.user_name }}</p>
    </div>
    <div>
        <p>{{ object.comment }}</p>
    </div>
    <hr>
    <div>
        <p>{{ object.commented_at }}</p>
    </div>


{% endblock %}

templates/events/event_detail.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/events/event_detail.css' %}">
{% endblock css %}

{% block content %}

    {% if event.image1 or event.image2 or event.image3 %}

        <div class="event-image-list">

            {% if event.image1 %}
            <div class="event-image1">
                <img class="image"  src="{{ event.image1.url }}">
            </div>
            {% endif %}


            {% if event.image2 %}
            <div>

                <img class="image"  src="{{ event.image2.url }}">
            </div>
            {% endif %}


            {% if event.image3 %}
                <div>
                    <img class="image" src="{{ event.image3.url }}">
                </div>
            {% endif %}

        </div>

    {% endif %}


    <div class="group">
        <div class="group-title">
            <h1><a href="{% url 'group:group_detail' event.posted_group.pk %}">{{ event.posted_group.name }}</a></h1>
        </div>

    </div>



    <div class="event-title">
        <span class="event-title-label">イベント</span>&nbsp;&nbsp;&nbsp;<small class="event-posted-at">投稿日&nbsp;&nbsp;&nbsp;{{ event.posted_at }}</small>
        <div class="event-title-body">
            <big>{{ event.title|linebreaksbr }}</big>
        </div>
    </div>



    <div class="event-about">
        <p>イベントについて</p>
        <div class="event-content">
            <p>{{ event.content|linebreaksbr }}</p>
        </div>
    </div>


    <div class="event event-prefecture">
        都道府県&nbsp;&nbsp;&nbsp;&nbsp;:
        &nbsp;&nbsp;&nbsp;&nbsp;
        {% for each_prefecture in event.prefecture.all %}
            <div class="event-tag">
                {{ each_prefecture }}
            </div>
        {% endfor %}

    </div>



    <div class="event event-day">
        {% if event.event_end_day %}

                開催期間&nbsp;&nbsp;:&nbsp;&nbsp;{{ event.event_day }} &nbsp;&nbsp;〜&nbsp;&nbsp; {{ event.event_end_day }}&nbsp;&nbsp;

        {% else %}

                開催日&nbsp;&nbsp;:&nbsp;&nbsp;{{ event.event_day }}

        {% endif %}
    </div>


    <div class="event-about">
        <p>詳細な活動場所</p>
        <div class="event-content">
            <p>{{ event.detail_place|linebreaksbr }}</p>
        </div>
    </div>
    {% if event.time_description %}
    <div class="event-about">
        <p>開催日時の補足情報</p>
        <div class="event-content">
            <p>{{ event.time_description|linebreaksbr }}</p>
        </div>
    </div>
    {% endif %}

{% if user.is_authenticated %}
<div class="join-event">
    <a class="btn btn-success" href="{% url 'events:event_join' event_pk=event.pk %}">イベントに参加</a>
</div>
{% endif %}

<div>



    {% if user.is_authenticated %}
        <form method="post" class="comment-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">コメントする</button>
        </form>
    {% endif %}

    <h2>コメント</h2>
    {% for comment in comments %}
        <div class="comment">
            <span class="comment-user">
                <a href="{% url 'users:user_detail' pk=comment.user.pk %}" class="user-link">
                    &nbsp;{{ comment.user.user.user_name }}
                </a>
            </span>
            <small>&nbsp;&nbsp;&nbsp;{{ comment.commented_at }}</small>
            <p>{{ comment.comment|linebreaksbr }}</p>
        </div>
    {% endfor %}
    {% if not comments %}
    <p>まだコメントはありません。</p>
    {% endif %}
</div>




{% endblock %}

templates/events/event_list.html
{% extends "base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/events/event_list.css' %}">
<link rel="stylesheet" href="{% static 'css/eyecatch_image.css' %}">

{% endblock css %}


{% block content %}





<div class="group group-title">

    <a href="{% url 'group:group_detail' group_pk=group.pk %}" class="group-link"></a>
    <h1>{{ group.name }}</h1>
</div>


<div class="header-column-wrapper">
    <div class="header-column header-column1">
        <a href="{% url 'group:group_detail' group_pk=group.pk %}" class="header-link"></a>グループ
    </div><!--
 --><div class="header-column header-column2">
        <a href="{% url 'events:event_list' group_pk=group.pk %}" class="header-link"></a>イベント
    </div><!--
    --><div class="header-column header-column3">
        <a href="{% url 'blogs:post_list' group_pk=group.pk %}" class="header-link"></a>ブログ
    </div>
</div>


<div class="event-list">
    <h2>投稿一覧</h2>
        {% for event in events %}
        <div class="event-wrapper">
            <div class="event">
                <a href="{% url 'events:event_detail' event_pk=event.pk %}" class="event-link"></a>
                    <div class="posted-at">
                        <small>{{ event.posted_at }}</small>
                    </div>
                <div class="event-body row">
                    <div class="col-12 col-sm-6 col-md-3 col-lg-4 post-image-parent">
                        <div class="image-wrapper">
                            <div class="image-subwrapper no-image">
                                {% if event.image1 %}
                                    <img class="image"  src="{{ event.image1.url }}">
                                {% else %}
                                No Image

                                {% endif %}
                            </div>
                        </div>

                    </div>
                    <div class="col-12 col-sm-6 col-md-6  offset-md-1 col-lg-6 post-sentence">
                        {% if event.title %}
                        <div class="title">
                            {{ event.title }}
                        </div>
                        {% endif %}


                        <div class="content">
                            {{ event.content|linebreaksbr|truncatechars:200 }}
                        </div>


                        <div class="place">
                            開催地&nbsp;&nbsp;:&nbsp;&nbsp;
                                {% for each_prefecture in event.prefecture.all %}
                                    <div class="tag">
                                        {{ each_prefecture }}
                                    </div>
                                {% endfor %}

                        </div>

                        <div class="time">
                            {% if event.event_end_day %}

                                    開催期間&nbsp;&nbsp;:&nbsp;&nbsp;{{ event.event_day }} &nbsp;&nbsp;〜&nbsp;&nbsp; {{ event.event_end_day }}&nbsp;&nbsp;

                            {% else %}

                                    開催日&nbsp;&nbsp;:&nbsp;&nbsp;{{ event.event_day }}

                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
            {% if is_administrator %}
                <span class="clearfix">
                    <a class="update" href="{% url 'events:update_event' pk=event.pk %}">更新</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="delete" href="{% url 'events:delete_event' pk=event.pk %}">削除</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="message-create" href="{% url 'message:create_event_message' event_pk=event.pk %}">イベントメッセージ作成</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="message-list" href="{% url 'message:event_message_list_for_host' event_pk=event.pk %}">イベントメッセージ一覧</a>
                </span>
            {% endif %}
        </div>



        {% endfor %}
    {% if events %}
        {% include 'pagination.html' %}
    {% else %}
        まだ投稿がありません。
    {% endif %}

</div>




{% endblock %}

templates/events/recent_event_list.html
{% extends "base.html" %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/eyecatch_image.css' %}">
    <link rel="stylesheet" href="{% static 'css/events/event_join_list.css' %}">
    <link rel="stylesheet" href="{% static 'css/events/recent_event_list.css' %}">

{% endblock css %}


{% block content %}

<div class="header-column-wrapper">
    <div class="header-column header-column1">
        <a href="{% url 'group:group_list' %}" class="header-link"></a>グループ
    </div><!--
 --><div class="header-column header-column2">
        <a href="{% url 'events:recent_event_list' %}" class="header-link"></a>イベント
    </div><!--
    --><div class="header-column header-column3">
        <a href="{% url 'blogs:recent_post_list' %}" class="header-link"></a>ブログ
    </div>
</div>






<div class="event-list">
    <h2>近日中のイベント</h2>
        {% for event in events %}
        <div class="event-wrapper">
            <div class="event">
                <a href="{% url 'events:event_detail' event_pk=event.pk %}" class="event-link"></a>
                    <div class="posted-at">
                        <small>{{ event.posted_at }}</small>
                    </div>
                <div class="event-body row">
                    <div class="col-xs-12 col-sm-6 col-md-3 col-lg-4 ">
                        <div class="image-wrapper">
                            <div class="image-subwrapper">
                                {% if event.image1 %}
                                    <img class="image"  src="{{ event.image1.url }}">
                                {% else %}
                                    <p class="no-image">No Image</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-6 col-md-6  offset-md-1 col-lg-6 post-sentence">
                        <div class="group">
                            グループ&nbsp;&nbsp;&nbsp;{{ event.posted_group.name }}
                        </div>
                        {% if event.title %}
                        <div class="title">
                            {{ event.title }}
                        </div>
                        {% endif %}


                        <div class="content">
                            {{ event.content|truncatechars:30 }}
                        </div>


                        <div class="place">
                            開催地&nbsp;&nbsp;:&nbsp;&nbsp;
                                {% for each_prefecture in event.prefecture.all %}
                                    <div class="tag">
                                        {{ each_prefecture }}
                                    </div>
                                {% endfor %}

                        </div>

                        <div class="time">
                            {% if event.event_end_day %}

                                    開催期間&nbsp;&nbsp;:&nbsp;&nbsp;{{ event.event_day }} &nbsp;&nbsp;〜&nbsp;&nbsp; {{ event.event_end_day }}&nbsp;&nbsp;

                            {% else %}

                                    開催日&nbsp;&nbsp;:&nbsp;&nbsp;{{ event.event_day }}

                            {% endif %}
                        </div>

                    </div>
                </div>
            </div>
        </div>


        {% endfor %}
    {% if events %}
        {% include 'pagination.html' %}
    {% else %}
        近日中のイベントはありません。
    {% endif %}
</div>






{% endblock %}